spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:5432/spring
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 2000
  jwt:
    secret:
      key: d361d69d7a07f080df82236885083386670454cf3e735b6bd8c0953dee0d8884
    time:
      expiration: 100000
  flyway:
    enabled: false
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop # Limpia tablas corruptas y permite al Seeder actuar de cero
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 1MB
  cache:
    type: none # Apaga la caché para evitar congelamiento de datos nulos en Postman

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server:
          requests: true

server:
  port: 9528